[workspace]
members = ["crates/*"]

[workspace.package]
name = "hyperlane_ztarknet"
description = "Implementation of the Hyperlane protocol on Starknet."
version = "0.0.1"
edition = "2024_07"
cairo-version = "2.12.2"
scarb-version = "2.12.2"
license-file = "../LICENSE"
readme = "../README.md"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[workspace.dependencies]
array = "0.6.0"
assert_macros = "2.12.2"
starknet = "2.12.2"
alexandria_bytes = "0.6.0"
alexandria_storage = "0.6.0"
alexandria_data_structures = "0.6.0"
alexandria_math = "0.6.0"
openzeppelin = "2.0.0"
snforge_std = "0.49.0"
snforge_scarb_plugin = "0.49.0"

[dev-dependencies]
snforge_std.workspace = true
cairo_test = "2.12.2"

[workspace.tool.fmt]
sort-module-level-items = true

[scripts]
test = "snforge test"

[workspace.tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
